### ISSUE TITLE
Switching only roughly correct

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#12]
We should mention somewhere, that you can't expect to have a precise (to the second) switching of your virtual switch and that it obviously depends on the interval you set up for your crontab.

Or is there a way to use the timer function of the switch instead for the actual switching?

**Comment by allan-gam** [comment]
Good point indeed! 

I'd strongly recommend using the suggested crontab interval of 1 minute. Advanced users might want to set it to a higher value but that would have consequences and it's easy to forget after some time. I don't think using 1 minute will put much strain on the system and it will certainly not block/delay/occupy the Domoticz event queue which I believe is most important. 

Will You make a note in the Wiki about what is to be expected when it comes to preciseness of switching?

There is currently no other way to schedule more precise switchings using GCal.

**Comment by four2six** [comment]
added that to the initial setup page and the troubleshooting page
