### ISSUE TITLE
Add initial setup to the wiki

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#14]
it lacks what you have to to enter during the gcal.py script

questions below.

Domoticz Time Zone [Europe/Stockholm]:Domoticz web interface IP address (or host name) [192.168.2.xxx]:
Domoticz web interface port number [8080]:
Domoticz web interface communication protocol (http or https) [http]:
Domoticz web interface user name (leave blank if no username is needed):
Domoticz web interface password (leave blank if no passord is needed):
Send calendar data with SCP to username@host (leave blank if domoticz is installed on this machine):
Send calendar data with SCP to remote directory (leave blank if domoticz is installed on this machine):
Directory for app logging and storing access tokens [/var/tmp]:
Calendar short name (Any unique name that You wish to use for this calendar):
Calendar public address (in form of an email address): something@group.calendar.google.com
Calendar OAuth2 Client ID: address@group.calendar.google.com
Calendar OAuth2 Client ID:
Calendar OAuth2 Client Secret: key
Number of minutes between refreshes of the calendar (5-1440) [180]:
Number of minutes before (negative) or after the event start time that you want the device to turn on. (-1440 to 1440) [0]:
Number of minutes before (negative) or after the event start time that you want the device to turn off. (-1440 to 1440) [0]:
Keyword. Event name and / or description to match. (Can be left blank or can be a keyword or phrase. Multiple keywords can be specified if separated by a semi-colon. If left blank, the script will trigger on every event.):

Can you explain the SCP thing?
Keyword: the keyword can be anywhere in the event name in Google calendar?

**Comment by allan-gam** [comment]
The SCP thing is when GCal is not running on the same host as Domoticz and you wish that the raw **Google Calendar Data json** files are sent to the Domoticz host by using scp. These are normally put in the tmp directory in the GCalData folder. These files contains a lot of information that might be of interest for advanced users. A script can be made to extract more data about the events.

Keyword matching is made against the Google Calendar event title and the description. Case is ignored.

**Comment by four2six** [comment]
added both to the wiki
