### ISSUE TITLE
No events

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#15]
![bildschirmfoto 2017-04-28 um 09 41 55](https://cloud.githubusercontent.com/assets/4852434/25519161/04fa8150-2bf7-11e7-99ab-028351f94e47.png)
this shows up when there are no events
the day before it had an event from 2000 to 2100
maybe that should be deleted?

**Comment by allan-gam** [comment]
I believe I have just fixed that issue. Please try the newest version. 

BTW, How are You doing updates?

Will the following work for You?

```
cd ~/GCal
git pull
```

**Comment by four2six** [comment]
normally i'm pulling every file onto a sd card, plug that into the raspberry, then manually copy it over and see if it still works. ;)

that worked, too, though

i'll add that to the wiki

and yes it fixed the issue, thank you
