### ISSUE TITLE
configuration script stops

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#2]
script stops with 

`Can not open the calendar file /var/tmp/GCalData/calendar-id@group.calendar.google.com.json <type 'exceptions.IOError'>`

where calendar-id is the ID i entered before

**Comment by four2six** [comment]
it probably means i have to copy the json file from the oauth setup somewhere? it doesn't state that in the instructions

**Comment by allan-gam** [comment]
That file will be fetched and saved automatically after a successful configuration.

1. Is that the first error message that You get?
2. Does the file and the /var/tmp/GCalData Directory exist?

**Comment by four2six** [comment]
1. yes
2. no
/var/tmp/ is empty

**Comment by allan-gam** [comment]
What was the last question you answered during setup?

**Comment by four2six** [comment]
Treat back-to-back events with the same name as one long event [Y/n] n

**Comment by four2six** [comment]
after that:
Created Domoticz virtual switch device (idx) : 190
Created Domoticz virtual switch device (idx) : 191
Can not open the calendar file /var/tmp/GCalData/xxx@group.calendar.google.com.json <type 'exceptions.IOError'>

**Comment by allan-gam** [comment]
I wonder if You can get any more information if you run the following from the console:
```/usr/bin/python /home/pi/GCal/gcal.py -v -d```

**Comment by allan-gam** [comment]
I believe I've found the problem. Please have a look in the /home/pi/GCal/.data/config.json

Please set back the "lastCheck" entry for the calendar to "2017-04-26 12:00:00"

Please let me know if it solves the problem. Thanks.

**Comment by four2six** [comment]
/usr/bin/python /home/pi/GCal/gcal.py -v -d
gives me

```
Debug is on
Google Calendar API for Domoticz Version 0.0.1 running on TTY console...
Found a total of : 1 calendar configuration entries.

Fetching Calendar : Google Calendar. Last fetched: 187 minutes ago. Interval: 180
/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/pi/GCal/.credentials/<123>.apps.googleusercontent.com.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))

Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/v2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar.readonly&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=<123>.apps.googleusercontent.com&access_type=offline
```

<123> being a long key, both the same. if you need more information about that, let me know

**Comment by four2six** [comment]
resetting the "lastCheck" entry for the calendar to "2017-04-26 12:00:00" in /home/pi/GCal/.data/config.json doesn't have any effect

**Comment by four2six** [comment]
oh wait, it is working now, somehow

**Comment by allan-gam** [comment]
Good. If You open that link in a browser and grant access. Do You get an access code that You can enter in the console?

**Comment by four2six** [comment]
the /usr/bin/python /home/pi/GCal/gcal.py -v -d above was before i changed the date

now it is:
```
Debug is on
Google Calendar API for Domoticz Version 0.0.1 running on TTY console...
Found a total of : 1 calendar configuration entries.

Skipping Calendar : Google Calendar. Last fetched: 153 minutes ago. Interval: 180
Can not open the calendar file /var/tmp/GCalData/c1fgnon19pl67h72mrmt9dtb5c@group.calendar.google.com.json <type 'exceptions.IOError'>
```

**Comment by four2six** [comment]
yes, if i open that link, i get a code

**Comment by four2six** [comment]
replacing the clientSecret with that code doesn't help, same error

**Comment by four2six** [comment]
still no /var/tmp/GCalData

**Comment by four2six** [comment]
shouldn't i be seeing an entry for this in 
[https://myaccount.google.com/permissions?pli=1](url)
?

**Comment by allan-gam** [comment]
The code that You received after granting permissions for GCal shall be entered in the setup dialogue. Did the script stop?

Please pive me a couple of minutes and I will check further. Thanks.

**Comment by four2six** [comment]
the setup dialogue? you mean entering it in /home/pi/GCal/.data/config.json ? in clientSecret ?

**Comment by four2six** [comment]
ok... i get what it should be
i entered the original clientSecret key
opened the link it offered, it gave me the authentication key.
i entered that key in gcal... it ask for that before

this it what it does
```
Debug is on
Google Calendar API for Domoticz Version 0.0.1 running on TTY console...
Found a total of : 1 calendar configuration entries.

Fetching Calendar : Google Calendar. Last fetched: 185 minutes ago. Interval: 180
/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/pi/GCal/.credentials/<123>.apps.googleusercontent.com.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))

Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/v2/<etc>

Enter verification code: <123>
Traceback (most recent call last):
  File "/home/pi/GCal/gcal.py", line 821, in <module>
    main(sys.argv[1:])
  File "/home/pi/GCal/gcal.py", line 817, in main
    list_calendars()
  File "/home/pi/GCal/gcal.py", line 755, in list_calendars
    syncWithGoogle(c)
  File "/home/pi/GCal/gcal.py", line 575, in syncWithGoogle
    credentials = get_credentials(c, cred_args)
  File "/home/pi/GCal/gcal.py", line 552, in get_credentials
    credentials = tools.run_flow(flow, store, flags)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/tools.py", line 246, in run_flow
    storage.put(credential)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 421, in put
    self.locked_put(credentials)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/file.py", line 83, in locked_put
    self._create_file_if_needed()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/file.py", line 70, in _create_file_if_needed
    open(self._filename, 'a+b').close()
IOError: [Errno 13] Permission denied: u'/home/pi/GCal/.credentials/<123>.apps.googleusercontent.com.json'
```

**Comment by allan-gam** [comment]
No, normally You are not supposed to enter anything in the config.json file. 

By the "Setup dialogue" I meant when You ran /usr/bin/python /home/pi/GCal/gcal.py. The script that You run on the console shall ask You for that code after displaying the "Userwarning" and telling You to visit the consent URL.  I will delete the credentials in my own installation so that I can check again that it works. I'll get back to You here.

I have updated the wiki.

**Comment by allan-gam** [comment]
OK, let me have a look

**Comment by allan-gam** [comment]
Are You logged in as user pi?
What are the permissions on /home/pi/GCal
`ls -la /home/pi/GCal`

**Comment by four2six** [comment]
```
pi@raspberrypi /var/tmp $ ls -la /home/pi/GCal
total 68
drwxr-xr-x  6 pi   pi    4096 Apr 27 14:17 .
drwxr-xr-x 15 pi   pi    4096 Apr 27 13:12 ..
drwxr-xr-x  2 root root  4096 Apr 27 14:17 .credentials
drwxr-xr-x  2 pi   pi    4096 Apr 27 13:16 .data
-rw-r--r--  1 pi   pi   33178 Apr 27 13:12 gcal.py
drwxr-xr-x  8 pi   pi    4096 Apr 27 13:12 .git
-rw-r--r--  1 pi   pi     125 Apr 27 13:12 .gitignore
drwxr-xr-x  2 pi   pi    4096 Apr 27 13:12 images
-rw-r--r--  1 pi   pi     487 Apr 27 13:12 README.md
```

**Comment by allan-gam** [comment]
OK. The .credentials directory is probably a tmpfs and it has caused the permissions to be unsufficient for user pi. 

Temporarily change the permissions for .credentials
sudo chown pi:pi /home/pi/GCal/.credentials;ls -la  /home/pi/GCal
I don't know if that change will be persistent, I would have to check that.

**Comment by four2six** [comment]
that helped
```
Authentication successful.
Storing credentials to /home/pi/GCal/.credentials/<123>.apps.googleusercontent.com.json
Getting the upcoming 10 events for calendar <123>@group.calendar.google.com
(u'2017-04-27T18:30:00+02:00', u'test')
GCal Status Google Calendar
N: <span style="color: grey;">test</span> !#1(1)!#<BR/><span style="font-weight: normal;">2017-04-27. From 18:30 to 19:30</span>
D: No future events found

GCal Google Calendar
N: Off
D: Off
```

**Comment by allan-gam** [comment]
Great!

**Comment by four2six** [comment]
.credentials remains pi:pi after reboot

**Comment by four2six** [comment]
want me to tell you proposed changes for the wiki?

**Comment by allan-gam** [comment]
Good that .credentials remains pi:pi after reboot. I will add it into the wiki. Rebooting will cause everything in the tmpfs directory to get lost but I believe that You know that already. ;)

I would be really happy for any suggestions for the wiki or I can assign you some permissions in case You wish to do the alteration by your self ;)

**Comment by four2six** [comment]
i didn't even know there was a solution to not let linux write to the sd card, so no tmpfs yet. until then, a reboot seems ok?

i guess entering it directly and you discarding it later seems to be the easier way ;-)

**Comment by allan-gam** [comment]
Then I wonder how the .credentials directory got root permissions ... Did You by any chance run the GCal script as user root or by issuing su ?

**Comment by four2six** [comment]
hmmm no, i didn't. but as i'm having problems getting the crontab to work i just noticed i made it a root crontab by sudoing crontab -e. and i did that right before i called the gcal.py for the first time.

**Comment by four2six** [comment]
yet my crontab still doesn't work

**Comment by four2six** [comment]
i stand corrected: it does seem to run. there seems to be an issue when you add a new event before the next one. it doesn't get updated.

**Comment by four2six** [comment]
is there a log file for gcal somewhere?

**Comment by allan-gam** [comment]
In order not to spam Google with calendar data requests too frequently, the GCal script will reflect changes that You have made in Your Google Calendar every "interval" minutes. Check in the /home/pi/GCal/.data/config.json file and change it to one minute if You need testing. (Don't forget to set it back to a higher value when You are finished testing) After doing that and the calendar data has been refreshed from Google, does it still not work? 

GCal is doing it's logging to Domoticz. Have a look in the Domoticz log.

**Comment by four2six** [comment]
ok, got it. that helped, thx
maybe add that to the wiki? are there more entries in the config.json that a user might want to change? if so, we should explain the json.

**Comment by allan-gam** [comment]
Yes, you've got a point there. People will need to alter the config.json But it will increase the risk that the file will be altered corrupt by user mistakes. But please feel free to add that to the wiki.
