### ISSUE TITLE
Add changing the interval for all calendars at once

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#20]
could you add an argument to edit all intervals at once?

**Comment by allan-gam** [comment]
Is this something that will be made regularly hence motivating implement a special argument for this? Why just fetching intervals? Will the proposed [Allow reconfiguring](https://github.com/allan-gam/GCal/issues/33) not fulfill that need and be more versatile?

**Comment by four2six** [comment]
it was just a personal request. for testing i need to turn intervals to "1" for all my calendars, and turn it back to 30 or whatever after i finished. which i generally forget ;)

**Comment by four2six** [comment]
but once you're in beta phase i can add that myself. 
not sure how the forking and unforking works here, but i will figure it out.

**Comment by allan-gam** [comment]
For a temporary task like that I believe it's better that you use the command line to change the config file. You can replace strings in files with sed, the bash command.

Change working directory:
`cd ~/GCal/.data`

Then make a backup of the config file:
`cp config.json config_backup.json`

Replace all the strings in a single command like:
` sed -i 's/"interval":30,/"interval":1,/g' config.json`

The above command will replace all intervals that are currently set to 30 to 1 minute. Alter the command to reverse it.

Cheers!

**Comment by four2six** [comment]
cool, thanks. want that in the wiki?

**Comment by allan-gam** [comment]
Thanks. I'm trying not to urge users to make manual edits of config files manually because my experience is that it will generate quite many support tickets.  I will continue my work towards having GCal make all the changes.
