### ISSUE TITLE
Multiple GCal calendars pointing at the same Google Calendar might not have enough data

### ISSUE THREAD

**Issue by allan-gam** [allan-gam/GCal#21]
Multiple GCal calendars pointing at the same Google Calendar might not have enough data. 

Calendar data is fetched from Google and stored locally. It's supposed to last for a certain period of time depending on time offsets and fetch interval etc. We don't fetch more events than necessary. However another calendar might be using the same Google resource and we have currently only one instance of the raw Google Calendar Data json file. That file gets overwritten if defining multiple calendars and that introduces a potential problem.

**Comment by four2six** [comment]
can't you set a variable that marks the file as being in use? and check on that in the other process?

**Comment by four2six** [comment]
or create a dummy file next to it and check on that

**Comment by allan-gam** [comment]
I will have a look at it.

**Comment by allan-gam** [comment]
Fixed.
