### ISSUE TITLE
Changing startDelta and endDelta in the config.json, shortName

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#22]
when i change it after the initial update, it doesn't make a change. i guess you just used it for the initial setup and it would be added to the settings of the switch device and to the name of the text device. why keep it in the json? people might be tempted to edit it and expect a change. or let it make a change, if you change it. but that might override the name they have changed in domoticz after the setup, right?

same goes for the shortName. if it is changed in Domoticz, shouldn't it be written back to the json?

**Comment by allan-gam** [comment]
Changing startDelta and endDelta in the config.json should definitely affect start offset and an end offset for that GCal entry. It works here. Are You sure about this?

**Comment by four2six** [comment]
early sunday riser ;-) hope you're doing well

yes, you're right, it does change the from and to time in the text device. it's not something i would have expected to find there, hence i didn't look. sorry. i was expecting it to be in the switch settings.

i find this behaviour a bit inconsistent, i think. in my case, it doesn't show me that the event is not at 1710, but actually at 1700, if i add a startdelta through the json after the initial setup. and I'm sure, in your case (the example in the wiki) the -80 in the name of the text device won't change, if you change the -80 in the jason. or does it?
and without you telling me i would looked for the -80 in the settings of the switch device, not in the from and to in the text device. and i would have thought the "real" event time to be 1110-1235.
i think this needs to be cleared up.
possibilities:
1. mirror all changes done in domoticz to the json and vice versa. so if i change the name in domoticz, write it to the json. if i change it in the json, write it to domoticz. this goes for name, the deltas and the deltas in the name of the text device and maybe even when i change the offset in the switch device. add (0:0) to the name of the text device if no delta is chosen during the initial setup.
2. don't store some of the details in the json so people don't expect a change to be mirrored, like the name. and those that are stored cause a predictable change in domoticz. 
3. leave it as it is and write about it in the wiki.

**Comment by allan-gam** [comment]
Hi there! Early mornings are underestimated :)

Letting users configure by editing a json config file is quite prune to generate all kind of errors and even though it may be convenient to do so by advanced users, I believe it's better that I develop a way to delete or to redefine a device using the script. I think it would be best that a typical user doesn't even have to know about a config file. Don't you think so? 

About device naming, here are the background thoughts. GCal helps creating Domoticz devices during setup. Domoticz devices need names. The reason that the script asks for a shortname during setup is that some public calendars and shared calendars have very long calendar addresses, like jkhkaskljshbw765ksj87snbakla88a87a@group.calendar.google.com Those names are not very helpful, I didn't want to use them. A user might define a bunch of GCal devices pointing to the same GCal Calendar (using different keywords and time deltas) hence I thought it would be helpful to assign _initial names_ in Domoticz that helps to distinguish between created Devices in Domoticz. GCal doesn't actually need a name for the calendar entry. I'd never thought that a user would like to keep the generated name. 

Initially I believe it's important to inform the user that the "-80" part in the device name is just a part of the "helpful" name initially assigned to the device, not a setting. I do realize that some users might want to expect that a change of the device name would alter the time deltas. We'd have to think about that a bit more I believe.

**Comment by four2six** [comment]
i think a config file is quite easy, especially after the initial setup has been done by the script.
i think there are some aspects to be considered seperately.
1. it shouldn't be possible to have different settings in the json and in domoticz. the short name should always be the same in both, the deltas (which they are already), etc. if you change things any way, either in domoticz or in the json or through a script, it should always be the same everywhere, at least after the script is run the next time. 
2. demanding a user should only make changes in one predefined fashion is not very clever, as the stupid user like me might not read the script or might just make mistakes. i did change the name in domoticz for one of the calendars without changing it in the json and it is already double thinking when you only have three calendars.
3. user variables: doesn't introducing user variables make the (-80:-80) obsolete? the name displayed in the text device should be something like "GCal " + shortname. the 80s should be either not mentioned (as the start and end time are changed from the initial event) or be in the setting of the switch and the time of the text device should be the original time of the event. and they should be in the user variables. or do a lot of user variables slow domoticz down? 
4. the easiest option would be to delete those entries from the json that don't cause a change in domoticz if you change them. but that would make the entries in the json less readable.

**Comment by allan-gam** [comment]
Thanks.

You can not change start- or end delta in Domoticz. 

I will think more about if we can remove the short name from GCal. I might use a number or the calendar address instead when creating devices in Domoticz. Please let me think about that for a while.

I haven't yet planned to use Domoticz user variables for configuring GCal. Any user variables would have the purpose of showing the current GCal entry status only, e.g. what event was tripped or numbers of remaining events etc.

**Comment by four2six** [comment]
what is the reason you didn't use the existing deltas settings for the switch, as for every other switch?

**Comment by allan-gam** [comment]
The start- and end delta for a GCal Calendar entry can be a positive or a negative value. It can move an event to occur back or forward in time compared what's defined in Google Calendar. Setting a Domoticz virtual switch's "On delay" or "Off delay" (If that's what you referred to?) is something completely different and it should be avoided. It would definitely interfere with the logic in GCal and such a delay can never be made negative.

For example, a negative  start delta can be set for a GCal calendar entry having it trigger earlier than what is originally scheduled in the Google Calendar.

**Comment by four2six** [comment]
yes, that's what i was referring to. i didn't know it couldn't be negative, it makes sense though.

**Comment by four2six** [comment]
after deleting hundreds of old variables from the old gcal... i should have written a script. why are you hesitant to use just those in the new gcal? effort? performance? mirroring?

**Comment by allan-gam** [comment]
I will add some variables, just haven't had the time to implement it yet.  ;)

**Comment by four2six** [comment]
ok, thx... even though that wasn't my intention of the question ;)

**Comment by allan-gam** [comment]
If you'd like to have user variables for GCal defined in Domoticz that GCal regularly synchronizes to GCal it would be possible to make but I'd prefer keeping the configuration in a single place. GCal certainly needs those variables locally and since they are read and updated frequently moving them to reside only in Domoticz would impact performance of both GCal and Domoticz.

In the future I may to consider to make Domoticz as a "module" to GCal hence allowing GCal to be used with any Home Automation system (if there is a module for it, that is...)

Cheers!
