### ISSUE TITLE
Data Normalization

### ISSUE THREAD

**Issue by allan-gam** [allan-gam/GCal#24]
Calendar credentials are now stored together with GCal Entries. We need to separate those credentials. The reason is to allow multiple GCal definitions using different time deltas and different keywords all pointing to a single Google Calendar. Calendar Credentials, last fetching time should not be kept together with each GCal entry.

**Comment by allan-gam** [comment]
The next release will require structural changes of the config file. After updating to version 0.2.0 that will release soon, the old config file should be deleted and a new setup should be run. In case that it would cause too much work for you, attach your config.json below (but remove your sensitive data first!!) and I am willing to make the needed modifications for you.

**Comment by four2six** [comment]
it won't, i can manage :-) but thanks for asking, very kind.

**Comment by allan-gam** [comment]
Implemented in version 0.2.0
