### ISSUE TITLE
wiki entry for deinstalling 

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#25]
- deinstalling GCal
- deinstalling BakSeeDaa´s Google Calendar for Domoticz

The BakSeeDaa´s Google Calendar for Domoticz has no uninstall script so if are not using it you'd have some Domoticz user variables named by the form GCalnnxxxXXXXXX that you can delete.

https://www.domoticz.com/forum/viewtopic.php?t=8333

**Comment by allan-gam** [comment]
UNINSTALLING instructions has been added in https://www.domoticz.com/forum/viewtopic.php?t=8333

**Comment by four2six** [comment]
this was also about how to uninstall the actual GCal.

**Comment by allan-gam** [comment]
;) I missed that

**Comment by four2six** [comment]
added both to the wiki

**Comment by allan-gam** [comment]
Great work! Thanks ;)

**Comment by four2six** [comment]
haha yeah, so proud of myself. that was a toughy. thanks for noticing. ;)
