### ISSUE TITLE
quotes from old forum entry

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#26]
reading through your initial post from the old gcal, i noticed you mentioned 

> Why would I want to do automate my Google Calendar
> Your imagination is the limit :lol: Maybe you would like to:
> Slowly dim up the light in your bedroom based on a work schedule in Google Calendar
> Disarm the entrance door if someone booked the laundry facilities room
> Turn Your partners "motorvärmare" (block heater) on 3 hours in advance of her his/her working schedule
> Turn on Your TV when Tampa Bay Buccaneers are playing
> Turn of the house heating whenever there is a public holiday in Thailand
> Be informed in your Sono's system one hour in advance if you are going to attend a meeting
> 
> 
> Stage of development
> The initial code from which BGCD derives, has been tested by many users on another HA platform. It's currently running well on Domoticz on Raspberry Pi and Synology hardware. There are currently no known issues. Don't use this software in situations where a software failure or a drop of internet connection can lead to any kind of damage or disturb your relation to your wife (or husband).
> 
> Your feedback is important. Please report any problems that you may encounter. You might as well post a reply here also if you haven't got any questions or encounter any problems.

sounds great, why not reuse it in the new wiki?
would call it alpha stage of development now?

**Comment by allan-gam** [comment]
I like the idea of reusing! ;)

I agree that it looks like alpha stage now when I'm re-engineering the data storage. That should normally not occur in Beta stage.

**Comment by four2six** [comment]
so eco friendly. hate it ;-) so swedish ;)

added it.
