### ISSUE TITLE
0 or 1 minute events in google calendar

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#29]
emme in the forum was right, there is an issue with events that start and end at the same minute. Google displays them just with one time. 
![bildschirmfoto 2017-05-03 um 13 12 34](https://cloud.githubusercontent.com/assets/4852434/25658265/465bd572-3002-11e7-9ca5-366dc3ba1b32.png)
the text device displays them with two times, both the same.

i tested it, and it doesn't switch the switch device. there's no switching in the protocol.

i would suggest setting the end time one minute higher, even though that would cause problems with those who don't run the script every minute. any other ideas?

**Comment by allan-gam** [comment]
Thanks! I will have a look at that.

**Comment by allan-gam** [comment]
This has been fixed in version 0.2.1

**Comment by allan-gam** [comment]
What has been fixed is one minute events.

0 duration events are expired as soon as they occur. How should a virtual switch in Domoticz be switched based on that?

**Comment by four2six** [comment]
it's a "momentary" event. like sunset or noon. or it could be a switch action. it would need a definition of how long that should be, as we need it to switch the switch for a certain amount of time. either make it a setting ("ZeroToMinutes" or whatever) or just make it 1 minute.

**Comment by allan-gam** [comment]
Add 1 minute to zero time event's end time. commit 9d66fad10176b55dbc0779514aedcb2d70bd19cd
