### ISSUE TITLE
Mysterious event had taken place in Sweden "last night"

### ISSUE THREAD

**Issue by allan-gam** [allan-gam/GCal#30]
It might seem that nothing has happened lately but the thing is that there has been quite some work done the latest days. I thought I'd be able to make a new release today but it turned out I have to take a dive into some UTF8 related issues first. Don't despair! 

Cheers!

**Comment by four2six** [comment]
at first i read "UFO related issues". in combination with the headline that had me a bit worried.
glad you're still on earth ;-)

take your time, you're doing so much. if i can be of any help, let me know.
