### ISSUE TITLE
exact keyword matching

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#31]
i'll be making a list what to test after a major update

what does the "Exact keyword" matching include? as opposed to any other keyword matching... that is.

**Comment by allan-gam** [comment]
**Exact (Event name or Description must match exactly)**
Keyword "Doodle" will match event name/description "Doodle"
Keyword "Doodle" will not match event name/description "Hello a Doodle"

**Not exact (Keyword can be found within event name or description)**
Keyword "Doodle" will match event name/description "Doodle"
Keyword "Doodle" will match event name/description "Hello a Doodle"

**Comment by four2six** [comment]
thx, got it, forgot about that setting in the json
