### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#32]
edit this post for testing procedure:

installation:
- initial configuration: /usr/bin/python /home/pi/GCal/gcal.py
- crontab
- offsets
- interval
- 
- 
- keyword matching
- exact keyword matching
- multiple keyword matching
- adding further calendars:  /usr/bin/python /home/pi/GCal/gcal.py -c
- 
Calendar Events:
- zero minute events
- full day events
-

**Comment by allan-gam** [comment]
Can these instructions be put in the Wiki or maybe in a file distributed in the project?  I'm trying to minimize the number of open issues for this project.

**Comment by four2six** [comment]
yes, i'll put it in a file
