### ISSUE TITLE
Unable to input port number on init

### ISSUE THREAD

**Issue by martinlarka** [allan-gam/GCal#35]
I was unable to input port number when trying to init gcal

> Domoticz web interface port number :80
That's not a valid port number. Try again:
Domoticz web interface port number :8080
That's not a valid port number. Try again:
Domoticz web interface port number :
That's not a valid port number. Try again:

Running on raspberry pi 3 with Debian jessie

**Comment by allan-gam** [comment]
Thanks!
Fixed in https://github.com/allan-gam/GCal/commit/b2e6bf02caefb98e5abd1cf3e362145d50008563
