### ISSUE TITLE
A new page in Wiki

### ISSUE THREAD

**Issue by allan-gam** [allan-gam/GCal#36]
I've created a new page in the Wiki for reconfiguring GCal. I'm hoping that the page for editing the config.json file can be deprecated. Would that be OK? 

Cheers!

**Comment by allan-gam** [comment]
Or maybe just have it remove from the TOC. I've linked to it now.

**Comment by four2six** [comment]
Sorry for having been silent for the last days, i was and still am ill... stupid viruses.

I've removed the json wiki from the content, haven't deleted the page itself it yet. maybe we need it during the next phase for some text, not sure.
