### ISSUE TITLE
Setting user variable of a calendar when problem 

### ISSUE THREAD

**Issue by djs45** [allan-gam/GCal#41]
Hello and thanks for your great job !
Is there a way to setting "trippedEvent" user variable to "ERROR : <type of error>" (for example) when there is a problem to retrieve events on calendar (wrong internet connection, wrong configuration or other) ?
For my domoticz projet, with this feature, i can turn to alternative planification of my home's heaters.
Thank you in advance

**Comment by allan-gam** [comment]
**PROJECT DISCONTINUED**
Unfortunately, I won't be able to continue development due to lack of time.
