### ISSUE TITLE
Create Wiki instructions how to edit the configuration file

### ISSUE THREAD

**Issue by allan-gam** [allan-gam/GCal#5]
Below are some configuration entries that need to be documented.

This is the maximum amount of time in minutes between refreshes of the calendar.
**interval**

This is the number of minutes before (negative) or after the event start time that you want the script to turn on. Applies to all events unless an event specific start/end delta is defined
**startDelta**

This is the number of minutes before (negative) or after the event start time that you want the script to turn off. Applies to all events unless an event specific start/end delta is defined
**endDelta**

If set this specifies the event name and / or description to match. Case is ignored. The behavior depends on the values set for exactKeyword and ignoreKeyword. Can be left blank or can be a keyword or a phrase. Multiple keywords can be specified if separated by a semi-colon ;
**keyword**

Set this to true if you want the script to match an event name exactly. Set to false if you want the script to match anywhere in the event name.
**exactKeyword**

Set this to true if you want the script to ignore any events where the event name matches the keyword or the description contains the keyword. Default is false.
**ignoreKeyword**

Set this to true if you want the script to ignore all day events. Default is false.
**ignoreAllDayEvent**

Set this to false so that back-to-back events with the same name will be treated as one long event. Useful for repeating all-day events. Default is true.
**retrip**

**Comment by four2six** [comment]
added
