### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#8]
you wrote

`When the setup is finished, in Domoticz, rename Your GCal text devices and Your GCal switch devices. You can find all created devices by selecting the room named "Google Calendars"`

what does it mean? you can rename them any way you like? you have to rename them before installing a second calendar?

**Comment by allan-gam** [comment]
It's not mandatory to rename the Domoticz devices. It's just a possibility and it won't break the functionality.

**Comment by four2six** [comment]
added to the wiki
