### ISSUE TITLE
'You'

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#9]
Is it a swedish quirk to capitalize 'You'? :)

**Comment by allan-gam** [comment]
"i" don't know but I think it was something I learned in school. I don't know why, probably my teacher learned it from a legal contract or so. It's obviously wrong so from now on I will try to remember to use the correct form. So, thank You !!!

;) ;) ;)

**Comment by four2six** [comment]
it's not a bug, it's a feature. we'll keep it :))
